/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as BrandWarmthRouteImport } from './routes/brand-warmth'
import { Route as BrandSoftRouteImport } from './routes/brand-soft'
import { Route as BrandFreshRouteImport } from './routes/brand-fresh'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeIndexRouteImport } from './routes/prototype/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as PrototypeSwipeListRouteImport } from './routes/prototype/swipe-list'
import { Route as PrototypeSwipeRouteImport } from './routes/prototype/swipe'
import { Route as PrototypeStoriesRouteImport } from './routes/prototype/stories'
import { Route as PrototypeRouletteRouteImport } from './routes/prototype/roulette'
import { Route as PrototypeQuickTapRouteImport } from './routes/prototype/quick-tap'
import { Route as PlaygroundSwipeListRouteImport } from './routes/playground/swipe-list'
import { Route as PlaygroundPrefsTabsRouteImport } from './routes/playground/prefs-tabs'
import { Route as PlaygroundPrefsStepperRouteImport } from './routes/playground/prefs-stepper'
import { Route as PlaygroundPrefsDrawerRouteImport } from './routes/playground/prefs-drawer'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as PlanWeekStartIndexRouteImport } from './routes/plan/$weekStart/index'
import { Route as PlanWeekStartPrepRouteImport } from './routes/plan/$weekStart/prep'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiRegenerateMealsRouteImport } from './routes/api/ai/regenerate-meals'
import { Route as ApiAiGeneratePrepRouteImport } from './routes/api/ai/generate-prep'
import { Route as ApiAiGenerateMoreMealsRouteImport } from './routes/api/ai/generate-more-meals'
import { Route as ApiAiGenerateMealsRouteImport } from './routes/api/ai/generate-meals'
import { Route as ApiAiGenerateMealImageRouteImport } from './routes/api/ai/generate-meal-image'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandWarmthRoute = BrandWarmthRouteImport.update({
  id: '/brand-warmth',
  path: '/brand-warmth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSoftRoute = BrandSoftRouteImport.update({
  id: '/brand-soft',
  path: '/brand-soft',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandFreshRoute = BrandFreshRouteImport.update({
  id: '/brand-fresh',
  path: '/brand-fresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeIndexRoute = PrototypeIndexRouteImport.update({
  id: '/prototype/',
  path: '/prototype/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSwipeListRoute = PrototypeSwipeListRouteImport.update({
  id: '/prototype/swipe-list',
  path: '/prototype/swipe-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSwipeRoute = PrototypeSwipeRouteImport.update({
  id: '/prototype/swipe',
  path: '/prototype/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeStoriesRoute = PrototypeStoriesRouteImport.update({
  id: '/prototype/stories',
  path: '/prototype/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRouletteRoute = PrototypeRouletteRouteImport.update({
  id: '/prototype/roulette',
  path: '/prototype/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeQuickTapRoute = PrototypeQuickTapRouteImport.update({
  id: '/prototype/quick-tap',
  path: '/prototype/quick-tap',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundSwipeListRoute = PlaygroundSwipeListRouteImport.update({
  id: '/playground/swipe-list',
  path: '/playground/swipe-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundPrefsTabsRoute = PlaygroundPrefsTabsRouteImport.update({
  id: '/playground/prefs-tabs',
  path: '/playground/prefs-tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundPrefsStepperRoute = PlaygroundPrefsStepperRouteImport.update({
  id: '/playground/prefs-stepper',
  path: '/playground/prefs-stepper',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundPrefsDrawerRoute = PlaygroundPrefsDrawerRouteImport.update({
  id: '/playground/prefs-drawer',
  path: '/playground/prefs-drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanWeekStartIndexRoute = PlanWeekStartIndexRouteImport.update({
  id: '/plan/$weekStart/',
  path: '/plan/$weekStart/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanWeekStartPrepRoute = PlanWeekStartPrepRouteImport.update({
  id: '/plan/$weekStart/prep',
  path: '/plan/$weekStart/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRegenerateMealsRoute = ApiAiRegenerateMealsRouteImport.update({
  id: '/api/ai/regenerate-meals',
  path: '/api/ai/regenerate-meals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGeneratePrepRoute = ApiAiGeneratePrepRouteImport.update({
  id: '/api/ai/generate-prep',
  path: '/api/ai/generate-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateMoreMealsRoute = ApiAiGenerateMoreMealsRouteImport.update({
  id: '/api/ai/generate-more-meals',
  path: '/api/ai/generate-more-meals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateMealsRoute = ApiAiGenerateMealsRouteImport.update({
  id: '/api/ai/generate-meals',
  path: '/api/ai/generate-meals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateMealImageRoute = ApiAiGenerateMealImageRouteImport.update({
  id: '/api/ai/generate-meal-image',
  path: '/api/ai/generate-meal-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand-fresh': typeof BrandFreshRoute
  '/brand-soft': typeof BrandSoftRoute
  '/brand-warmth': typeof BrandWarmthRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/playground/prefs-drawer': typeof PlaygroundPrefsDrawerRoute
  '/playground/prefs-stepper': typeof PlaygroundPrefsStepperRoute
  '/playground/prefs-tabs': typeof PlaygroundPrefsTabsRoute
  '/playground/swipe-list': typeof PlaygroundSwipeListRoute
  '/prototype/quick-tap': typeof PrototypeQuickTapRoute
  '/prototype/roulette': typeof PrototypeRouletteRoute
  '/prototype/stories': typeof PrototypeStoriesRoute
  '/prototype/swipe': typeof PrototypeSwipeRoute
  '/prototype/swipe-list': typeof PrototypeSwipeListRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
  '/api/ai/generate-meal-image': typeof ApiAiGenerateMealImageRoute
  '/api/ai/generate-meals': typeof ApiAiGenerateMealsRoute
  '/api/ai/generate-more-meals': typeof ApiAiGenerateMoreMealsRoute
  '/api/ai/generate-prep': typeof ApiAiGeneratePrepRoute
  '/api/ai/regenerate-meals': typeof ApiAiRegenerateMealsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$weekStart/prep': typeof PlanWeekStartPrepRoute
  '/plan/$weekStart/': typeof PlanWeekStartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand-fresh': typeof BrandFreshRoute
  '/brand-soft': typeof BrandSoftRoute
  '/brand-warmth': typeof BrandWarmthRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/playground/prefs-drawer': typeof PlaygroundPrefsDrawerRoute
  '/playground/prefs-stepper': typeof PlaygroundPrefsStepperRoute
  '/playground/prefs-tabs': typeof PlaygroundPrefsTabsRoute
  '/playground/swipe-list': typeof PlaygroundSwipeListRoute
  '/prototype/quick-tap': typeof PrototypeQuickTapRoute
  '/prototype/roulette': typeof PrototypeRouletteRoute
  '/prototype/stories': typeof PrototypeStoriesRoute
  '/prototype/swipe': typeof PrototypeSwipeRoute
  '/prototype/swipe-list': typeof PrototypeSwipeListRoute
  '/playground': typeof PlaygroundIndexRoute
  '/prototype': typeof PrototypeIndexRoute
  '/api/ai/generate-meal-image': typeof ApiAiGenerateMealImageRoute
  '/api/ai/generate-meals': typeof ApiAiGenerateMealsRoute
  '/api/ai/generate-more-meals': typeof ApiAiGenerateMoreMealsRoute
  '/api/ai/generate-prep': typeof ApiAiGeneratePrepRoute
  '/api/ai/regenerate-meals': typeof ApiAiRegenerateMealsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$weekStart/prep': typeof PlanWeekStartPrepRoute
  '/plan/$weekStart': typeof PlanWeekStartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand-fresh': typeof BrandFreshRoute
  '/brand-soft': typeof BrandSoftRoute
  '/brand-warmth': typeof BrandWarmthRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/signup': typeof SignupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/playground/prefs-drawer': typeof PlaygroundPrefsDrawerRoute
  '/playground/prefs-stepper': typeof PlaygroundPrefsStepperRoute
  '/playground/prefs-tabs': typeof PlaygroundPrefsTabsRoute
  '/playground/swipe-list': typeof PlaygroundSwipeListRoute
  '/prototype/quick-tap': typeof PrototypeQuickTapRoute
  '/prototype/roulette': typeof PrototypeRouletteRoute
  '/prototype/stories': typeof PrototypeStoriesRoute
  '/prototype/swipe': typeof PrototypeSwipeRoute
  '/prototype/swipe-list': typeof PrototypeSwipeListRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
  '/api/ai/generate-meal-image': typeof ApiAiGenerateMealImageRoute
  '/api/ai/generate-meals': typeof ApiAiGenerateMealsRoute
  '/api/ai/generate-more-meals': typeof ApiAiGenerateMoreMealsRoute
  '/api/ai/generate-prep': typeof ApiAiGeneratePrepRoute
  '/api/ai/regenerate-meals': typeof ApiAiRegenerateMealsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$weekStart/prep': typeof PlanWeekStartPrepRoute
  '/plan/$weekStart/': typeof PlanWeekStartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/brand-fresh'
    | '/brand-soft'
    | '/brand-warmth'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/preferences'
    | '/signup'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/playground/prefs-drawer'
    | '/playground/prefs-stepper'
    | '/playground/prefs-tabs'
    | '/playground/swipe-list'
    | '/prototype/quick-tap'
    | '/prototype/roulette'
    | '/prototype/stories'
    | '/prototype/swipe'
    | '/prototype/swipe-list'
    | '/playground/'
    | '/prototype/'
    | '/api/ai/generate-meal-image'
    | '/api/ai/generate-meals'
    | '/api/ai/generate-more-meals'
    | '/api/ai/generate-prep'
    | '/api/ai/regenerate-meals'
    | '/api/auth/$'
    | '/plan/$weekStart/prep'
    | '/plan/$weekStart/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/brand-fresh'
    | '/brand-soft'
    | '/brand-warmth'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/preferences'
    | '/signup'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/playground/prefs-drawer'
    | '/playground/prefs-stepper'
    | '/playground/prefs-tabs'
    | '/playground/swipe-list'
    | '/prototype/quick-tap'
    | '/prototype/roulette'
    | '/prototype/stories'
    | '/prototype/swipe'
    | '/prototype/swipe-list'
    | '/playground'
    | '/prototype'
    | '/api/ai/generate-meal-image'
    | '/api/ai/generate-meals'
    | '/api/ai/generate-more-meals'
    | '/api/ai/generate-prep'
    | '/api/ai/regenerate-meals'
    | '/api/auth/$'
    | '/plan/$weekStart/prep'
    | '/plan/$weekStart'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/brand-fresh'
    | '/brand-soft'
    | '/brand-warmth'
    | '/design-system'
    | '/login'
    | '/onboarding'
    | '/preferences'
    | '/signup'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/playground/prefs-drawer'
    | '/playground/prefs-stepper'
    | '/playground/prefs-tabs'
    | '/playground/swipe-list'
    | '/prototype/quick-tap'
    | '/prototype/roulette'
    | '/prototype/stories'
    | '/prototype/swipe'
    | '/prototype/swipe-list'
    | '/playground/'
    | '/prototype/'
    | '/api/ai/generate-meal-image'
    | '/api/ai/generate-meals'
    | '/api/ai/generate-more-meals'
    | '/api/ai/generate-prep'
    | '/api/ai/regenerate-meals'
    | '/api/auth/$'
    | '/plan/$weekStart/prep'
    | '/plan/$weekStart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BrandFreshRoute: typeof BrandFreshRoute
  BrandSoftRoute: typeof BrandSoftRoute
  BrandWarmthRoute: typeof BrandWarmthRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  SignupRoute: typeof SignupRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PlaygroundPrefsDrawerRoute: typeof PlaygroundPrefsDrawerRoute
  PlaygroundPrefsStepperRoute: typeof PlaygroundPrefsStepperRoute
  PlaygroundPrefsTabsRoute: typeof PlaygroundPrefsTabsRoute
  PlaygroundSwipeListRoute: typeof PlaygroundSwipeListRoute
  PrototypeQuickTapRoute: typeof PrototypeQuickTapRoute
  PrototypeRouletteRoute: typeof PrototypeRouletteRoute
  PrototypeStoriesRoute: typeof PrototypeStoriesRoute
  PrototypeSwipeRoute: typeof PrototypeSwipeRoute
  PrototypeSwipeListRoute: typeof PrototypeSwipeListRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  PrototypeIndexRoute: typeof PrototypeIndexRoute
  ApiAiGenerateMealImageRoute: typeof ApiAiGenerateMealImageRoute
  ApiAiGenerateMealsRoute: typeof ApiAiGenerateMealsRoute
  ApiAiGenerateMoreMealsRoute: typeof ApiAiGenerateMoreMealsRoute
  ApiAiGeneratePrepRoute: typeof ApiAiGeneratePrepRoute
  ApiAiRegenerateMealsRoute: typeof ApiAiRegenerateMealsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PlanWeekStartPrepRoute: typeof PlanWeekStartPrepRoute
  PlanWeekStartIndexRoute: typeof PlanWeekStartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-warmth': {
      id: '/brand-warmth'
      path: '/brand-warmth'
      fullPath: '/brand-warmth'
      preLoaderRoute: typeof BrandWarmthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-soft': {
      id: '/brand-soft'
      path: '/brand-soft'
      fullPath: '/brand-soft'
      preLoaderRoute: typeof BrandSoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-fresh': {
      id: '/brand-fresh'
      path: '/brand-fresh'
      fullPath: '/brand-fresh'
      preLoaderRoute: typeof BrandFreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/': {
      id: '/prototype/'
      path: '/prototype'
      fullPath: '/prototype/'
      preLoaderRoute: typeof PrototypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/swipe-list': {
      id: '/prototype/swipe-list'
      path: '/prototype/swipe-list'
      fullPath: '/prototype/swipe-list'
      preLoaderRoute: typeof PrototypeSwipeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/swipe': {
      id: '/prototype/swipe'
      path: '/prototype/swipe'
      fullPath: '/prototype/swipe'
      preLoaderRoute: typeof PrototypeSwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/stories': {
      id: '/prototype/stories'
      path: '/prototype/stories'
      fullPath: '/prototype/stories'
      preLoaderRoute: typeof PrototypeStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/roulette': {
      id: '/prototype/roulette'
      path: '/prototype/roulette'
      fullPath: '/prototype/roulette'
      preLoaderRoute: typeof PrototypeRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/quick-tap': {
      id: '/prototype/quick-tap'
      path: '/prototype/quick-tap'
      fullPath: '/prototype/quick-tap'
      preLoaderRoute: typeof PrototypeQuickTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/swipe-list': {
      id: '/playground/swipe-list'
      path: '/playground/swipe-list'
      fullPath: '/playground/swipe-list'
      preLoaderRoute: typeof PlaygroundSwipeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/prefs-tabs': {
      id: '/playground/prefs-tabs'
      path: '/playground/prefs-tabs'
      fullPath: '/playground/prefs-tabs'
      preLoaderRoute: typeof PlaygroundPrefsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/prefs-stepper': {
      id: '/playground/prefs-stepper'
      path: '/playground/prefs-stepper'
      fullPath: '/playground/prefs-stepper'
      preLoaderRoute: typeof PlaygroundPrefsStepperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/prefs-drawer': {
      id: '/playground/prefs-drawer'
      path: '/playground/prefs-drawer'
      fullPath: '/playground/prefs-drawer'
      preLoaderRoute: typeof PlaygroundPrefsDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$weekStart/': {
      id: '/plan/$weekStart/'
      path: '/plan/$weekStart'
      fullPath: '/plan/$weekStart/'
      preLoaderRoute: typeof PlanWeekStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$weekStart/prep': {
      id: '/plan/$weekStart/prep'
      path: '/plan/$weekStart/prep'
      fullPath: '/plan/$weekStart/prep'
      preLoaderRoute: typeof PlanWeekStartPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/regenerate-meals': {
      id: '/api/ai/regenerate-meals'
      path: '/api/ai/regenerate-meals'
      fullPath: '/api/ai/regenerate-meals'
      preLoaderRoute: typeof ApiAiRegenerateMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-prep': {
      id: '/api/ai/generate-prep'
      path: '/api/ai/generate-prep'
      fullPath: '/api/ai/generate-prep'
      preLoaderRoute: typeof ApiAiGeneratePrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-more-meals': {
      id: '/api/ai/generate-more-meals'
      path: '/api/ai/generate-more-meals'
      fullPath: '/api/ai/generate-more-meals'
      preLoaderRoute: typeof ApiAiGenerateMoreMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-meals': {
      id: '/api/ai/generate-meals'
      path: '/api/ai/generate-meals'
      fullPath: '/api/ai/generate-meals'
      preLoaderRoute: typeof ApiAiGenerateMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-meal-image': {
      id: '/api/ai/generate-meal-image'
      path: '/api/ai/generate-meal-image'
      fullPath: '/api/ai/generate-meal-image'
      preLoaderRoute: typeof ApiAiGenerateMealImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BrandFreshRoute: BrandFreshRoute,
  BrandSoftRoute: BrandSoftRoute,
  BrandWarmthRoute: BrandWarmthRoute,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  SignupRoute: SignupRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PlaygroundPrefsDrawerRoute: PlaygroundPrefsDrawerRoute,
  PlaygroundPrefsStepperRoute: PlaygroundPrefsStepperRoute,
  PlaygroundPrefsTabsRoute: PlaygroundPrefsTabsRoute,
  PlaygroundSwipeListRoute: PlaygroundSwipeListRoute,
  PrototypeQuickTapRoute: PrototypeQuickTapRoute,
  PrototypeRouletteRoute: PrototypeRouletteRoute,
  PrototypeStoriesRoute: PrototypeStoriesRoute,
  PrototypeSwipeRoute: PrototypeSwipeRoute,
  PrototypeSwipeListRoute: PrototypeSwipeListRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  PrototypeIndexRoute: PrototypeIndexRoute,
  ApiAiGenerateMealImageRoute: ApiAiGenerateMealImageRoute,
  ApiAiGenerateMealsRoute: ApiAiGenerateMealsRoute,
  ApiAiGenerateMoreMealsRoute: ApiAiGenerateMoreMealsRoute,
  ApiAiGeneratePrepRoute: ApiAiGeneratePrepRoute,
  ApiAiRegenerateMealsRoute: ApiAiRegenerateMealsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PlanWeekStartPrepRoute: PlanWeekStartPrepRoute,
  PlanWeekStartIndexRoute: PlanWeekStartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
